spring.application.name=backendobservatorio

# URL aponta para o arquivo local. Se o arquivo não existir, o Hibernate criará um novo.
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite não exige usuário e senha, mas o Spring pode pedir que as propriedades existam (deixe vazio)
spring.datasource.username=
spring.datasource.password=

# Dialeto necessário para o Hibernate traduzir os comandos para a sintaxe SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true